/**
 * ntfy.sh Channel Admin Settings
 *
 * Registers the settings UI for ntfy notification channels.
 * Supports multiple ntfy topics/destinations.
 *
 * @package
 */

import './style.css';

import { addFilter } from '@wordpress/hooks';
import { CheckboxControl, TextControl } from '@wordpress/components';
import { __ } from '@wordpress/i18n';

/**
 * Render ntfy channel settings.
 * @param root0
 * @param root0.settings
 * @param root0.onChange
 * @param root0.channelId
 */
function NtfyChannelSettings( { settings, onChange, channelId } ) {
	// Topic is generated by backend if not set.
	const currentTopic = settings.topic || '';
	const server =
		settings.server ||
		window.workflowNtfy?.defaultServer ||
		'https://ntfy.sh';

	return (
		<>
			<TextControl
				__next40pxDefaultSize
				__nextHasNoMarginBottom
				label={ __( 'Name', 'workflow-ntfy' ) }
				value={ settings.name || '' }
				onChange={ ( value ) => onChange( 'name', value ) }
				placeholder={ __( 'e.g., ntfy (Alerts)', 'workflow-ntfy' ) }
				help={ __(
					'A friendly name to identify this ntfy destination',
					'workflow-ntfy'
				) }
			/>
			<CheckboxControl
				label={ __( 'Enable notifications', 'workflow-ntfy' ) }
				checked={ settings.enabled ?? false }
				onChange={ ( value ) => onChange( 'enabled', value ) }
				help={
					<>
						{ __( 'Free push notifications.', 'workflow-ntfy' ) }{ ' ' }
						<a
							href="https://ntfy.sh"
							target="_blank"
							rel="noreferrer"
						>
							{ __( 'Learn more', 'workflow-ntfy' ) }
						</a>
					</>
				}
				__nextHasNoMarginBottom
			/>
			<TextControl
				__next40pxDefaultSize
				__nextHasNoMarginBottom
				label={ __( 'Topic', 'workflow-ntfy' ) }
				value={ settings.topic || '' }
				onChange={ ( value ) => onChange( 'topic', value ) }
				help={
					currentTopic ? (
						<>
							{ __(
								'Topics are public and globally unique across all ntfy users. Use hard-to-guess names.',
								'workflow-ntfy'
							) }{ ' ' }
							<a
								href={ `${ server }/${ currentTopic }` }
								target="_blank"
								rel="noreferrer"
							>
								{ __( 'Open →', 'workflow-ntfy' ) }
							</a>
						</>
					) : (
						__(
							'Topic will be auto-generated when saved.',
							'workflow-ntfy'
						)
					)
				}
			/>
			<TextControl
				__next40pxDefaultSize
				__nextHasNoMarginBottom
				label={ __( 'Server', 'workflow-ntfy' ) }
				value={ settings.server || '' }
				onChange={ ( value ) => onChange( 'server', value ) }
				type="url"
				placeholder="https://ntfy.sh"
				help={ __(
					'Use ntfy.sh or your self-hosted server',
					'workflow-ntfy'
				) }
			/>
		</>
	);
}

// Register the settings component for ntfy channels.
addFilter(
	'vipWorkflow.channelSettingsComponent',
	'workflow-channel-ntfy',
	( component, channelId, props ) => {
		// Handle all ntfy channels (ntfy-default, ntfy-xxx, etc.)
		if ( channelId.startsWith( 'ntfy-' ) ) {
			return <NtfyChannelSettings { ...props } channelId={ channelId } />;
		}
		return component;
	}
);

// Register ntfy as a channel group with add/remove functionality.
addFilter( 'vipWorkflow.channelGroups', 'workflow-channel-ntfy', ( groups ) => {
	return [
		...groups,
		{
			prefix: 'ntfy-',
			label: __( 'ntfy.sh', 'workflow-ntfy' ),
			addEndpoint: '/workflow-ntfy/v1/destinations',
			newName: __( 'ntfy (New)', 'workflow-ntfy' ),
			defaultConfig: {
				server: 'https://ntfy.sh',
				topic: '',
				enabled: true,
			},
		},
	];
} );
